// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3gOvaR7igSPQ0Vdoyrad2DdpaV_vx5sM',
    appId: '1:48764843388:web:1a413f617dae565dd7a0f9',
    messagingSenderId: '48764843388',
    projectId: 'chat-app-e0ddf',
    authDomain: 'chat-app-e0ddf.firebaseapp.com',
    storageBucket: 'chat-app-e0ddf.firebasestorage.app',
    measurementId: 'G-9742JX5KFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADAzNCN5YV7hU5O05MYrFRf_1dbcVMOUM',
    appId: '1:48764843388:android:4fc236bed5e21945d7a0f9',
    messagingSenderId: '48764843388',
    projectId: 'chat-app-e0ddf',
    storageBucket: 'chat-app-e0ddf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFvrK10SWklBxiGOv5zVeg-GxGOBbaBVM',
    appId: '1:48764843388:ios:f6867d8240c32019d7a0f9',
    messagingSenderId: '48764843388',
    projectId: 'chat-app-e0ddf',
    storageBucket: 'chat-app-e0ddf.firebasestorage.app',
    iosBundleId: 'com.example.scholarChatSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFvrK10SWklBxiGOv5zVeg-GxGOBbaBVM',
    appId: '1:48764843388:ios:f6867d8240c32019d7a0f9',
    messagingSenderId: '48764843388',
    projectId: 'chat-app-e0ddf',
    storageBucket: 'chat-app-e0ddf.firebasestorage.app',
    iosBundleId: 'com.example.scholarChatSetup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3gOvaR7igSPQ0Vdoyrad2DdpaV_vx5sM',
    appId: '1:48764843388:web:e33c567491502d1ed7a0f9',
    messagingSenderId: '48764843388',
    projectId: 'chat-app-e0ddf',
    authDomain: 'chat-app-e0ddf.firebaseapp.com',
    storageBucket: 'chat-app-e0ddf.firebasestorage.app',
    measurementId: 'G-G02Z2E37B0',
  );

}